name = "sensitive_orange_sole-fcf6"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "sensitive_orange_sole-fcf6-debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "sensitive_orange_sole-fcf6-release.wasm"
command = "npm run build:release"
